name: full_screen_date_picker
description: Flutter package that gives you the ability to pick a date in beautiful full screen UI.
version: 0.0.2+2
homepage: https://github.com/omzer/full_screen_date_picker

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
